nosens_wcs_homepage:
    path:     /home
    defaults: { _controller: NosensWcsBundle:Wcs:Home }


wcs_card_add:
    path:     /vu
    defaults: { _controller: NosensWcsBundle:Wcs:Wcsadd}
    methods:  [GET, POST]

wcs_card_delete:
    path:     /{id}/delete
    defaults: { _controller: NosensWcsBundle:Wcs:Wcsdelete}
    methods:  [GET, POST]

nosens_exo:
    path:      /exo
    defaults: { _controller: NosensWcsBundle:Exo:Exo}