Nosens\WcsBundle\Entity\Card:
    type: entity
    table: null
    repositoryClass: Nosens\WcsBundle\Repository\CardRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        date:
            type: datetime
            nullable: true
        content:
            type: string
            length: 255
            nullable: true
        link:
            type: string
            length: 255
            nullable: true

    manyToOne:
        categories:
            targetEntity: Nosens\WcsBundle\Entity\Categorie
            inversedBy: cards


#    oneToOne:
#         picture:
#             targetEntity: WcsBundle\Entity\Picture
#             cascade: ['all']